<?php
include("init.php");
include("../entities/inpatient.php");

if(isset($_POST['submit']))
{
//    echo 'hello';
 if( empty($_POST['pat_id']) || empty($_POST['yy'])|| empty($_POST['mm'])|| empty($_POST['dd'])
         || empty($_POST['nursing_charges'])|| empty($_POST['medical_charges']) )
{
//////////////////////////create a alert box here
     
}
else
{
$pat_id=$_POST['pat_id'];
$departure_date=$_POST['yy']."-".$_POST['mm']."-".$_POST['dd'];
$nursing_charges=$_POST['nursing_charges'];
$medical_charges=$_POST['medical_charges'];



$add_inpat_depart = new Inpatient();
$add=$add_inpat_depart->inpat_depart($pat_id,$departure_date,$nursing_charges,$medical_charges);
}

}

?>

















<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Untitled Form</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>
<script type="text/javascript" src="calendar.js"></script>
</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Untitled Form</a></h1>
		<form id="form_3727" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Untitled Form</h2>
			<p>This is your form description. Click here to edit.</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Patient_Id </label>
		<div>
			<input id="element_1" name="element_1" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Start_Date </label>
		<span>
			<input id="element_2_1" name="element_2_1" class="element text" size="2" maxlength="2" value="" type="text"> /
			<label for="element_2_1">MM</label>
		</span>
		<span>
			<input id="element_2_2" name="element_2_2" class="element text" size="2" maxlength="2" value="" type="text"> /
			<label for="element_2_2">DD</label>
		</span>
		<span>
	 		<input id="element_2_3" name="element_2_3" class="element text" size="4" maxlength="4" value="" type="text">
			<label for="element_2_3">YYYY</label>
		</span>
	
		<span id="calendar_2">
			<img id="cal_img_2" class="datepicker" src="calendar.gif" alt="Pick a date.">	
		</span>
		<script type="text/javascript">
			Calendar.setup({
			inputField	 : "element_2_3",
			baseField    : "element_2",
			displayArea  : "calendar_2",
			button		 : "cal_img_2",
			ifFormat	 : "%B %e, %Y",
			onSelect	 : selectDate
			});
		</script>
		 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Advance </label>
		<div>
			<input id="element_3" name="element_3" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_4" >
		<label class="description" for="element_4">Room/Ward </label>
		<div>
		<select class="element select medium" id="element_4" name="element_4"> 
			<option value="" selected="selected"></option>
<option value="1" >Room</option>
<option value="2" >Ward</option>

		</select>
		</div> 
		</li>		
                <li id="li_5" >
		<label class="description" for="element_5">Room_Type </label>
		<div>
		<select class="element select medium" id="element_5" name="element_5"> 
			<option value="" selected="selected"></option>
<option value="1" >First option</option>
<option value="2" >Second option</option>
<option value="3" >Third option</option>

		</select>
		</div> 
		</li>
                <?php
                echo '<li id="li_6" >';
		echo '<label class="description" for="element_6">Ward_Name </label>';
		echo '<div>';
		echo'<select class="element select medium" id="element_6" name="element_6"> ';
			echo'<option value="" selected="selected"></option>';
echo'<option value="1" >First option</option>';
echo'<option value="2" >Second option</option>';
echo'<option value="3" >Third option</option>';

		echo'</select>';
		echo'</div> ';
		echo'</li>';
		?>	
					<li class="buttons">
			    <input type="hidden" name="form_id" value="3727" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>